# Generated by Django 5.2.7 on 2026-01-20 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='dish',
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Presentación')),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio extra')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='restaurant.dish', verbose_name='Platillo')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'unique_together': {('dish', 'name')},
            },
        ),
        migrations.AddField(
            model_name='saleitem',
            name='presentation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='restaurant.presentation', verbose_name='Presentación'),
            preserve_default=False,
        ),
    ]
