# Generated by Django 5.2.7 on 2026-01-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_remove_saleitem_dish_alter_saleitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio unitario'),
        ),
    ]
