# Generated by Django 5.2.7 on 2026-01-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_saleitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Completada'),
        ),
    ]
